on:
  workflow_dispatch:
    inputs:
      runs-on: 
        description: Select the runnter type to run the tests on
        type: choice
        options:
          - ubuntu-22.04
          - ubuntu-24.04
          - macos-14
          - macos-13
          - windows-2019
          - windows-2022
        default: ubuntu-22.04
      vcpkg-configuration:
        description: Configuration to activate
        type: string
        default: |
          {
            "registries": [
              {
                "kind": "artifact",
                "location": "https://artifacts.tools.arm.com/vcpkg-registry",
                "name": "arm"
              }
            ],
            "requires": {
              "arm:tools/open-cmsis-pack/cmsis-toolbox": "^2.0.0-0"
            }
          }
      packlist:
          description: List of packs to pre-install
          type: string
          default: |
            ARM.CMSIS\n
            ARM.Cortex_DFP

env:
  CMSIS_PACK_ROOT: ${{ github.workspace }}/.packs

jobs:
  test:
    name: Compile example
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Create vcpkg-configuration json
        uses: "DamianReeves/write-file-action@v1.3"
        with:
          path: vcpkg-configuration.json
          write-mode: overwrite
          contents: |
            ${{ inputs.vcpkg-configuration }}

      - name: Activate vcpkg environment
        uses: ARM-software/cmsis-actions/vcpkg@v1

      - name: Cache pack root
        uses: actions/cache@v4
        with:
          key: cmsis-pack-root
          path: |
            ${{ env.CMSIS_PACK_ROOT }}/.Download
            ${{ env.CMSIS_PACK_ROOT }}/.Web

      - name: Install packs
        run: |
          printf "${{ inputs.packlist }}" > packlist.txt
          if [ ! -d ${{ env.CMSIS_PACK_ROOT }} ]; then
            mkdir -p ${{ env.CMSIS_PACK_ROOT }}
            cpackget init https://www.keil.com/pack/index.pidx
          fi
          cpackget update-index
          cpackget add -v -a -f packlist.txt
